# sudo-enabled Ubuntu Trusty
dist: trusty

# running each build in docker container - cause speed
sudo: false

language: python
python: "2.7"

branches:
  only:
  - master
  - travis

install:

  # getting modules
  - pip install ansible==2.4.0 molecule apache-libcloud
  - ansible --version

script:

  # validating ansible tasks
  - find tasks -type f -exec echo Validating {} \; -exec ansible-lint {} \;

notifications:
  email: false