dist: trusty
sudo: false

language: python
python: '2.7'

branches:
  only:
  - master
  - travis

env:
  global:
  - GCE_CREDENTIALS_FILE="${TRAVIS_BUILD_DIR}/gcekey.json"
  # project id
  - secure: "DAM6EhSUmz6moRWheMUfDOHWOcDaBq2JbAstcuVboZ4ThxreQKjsZoms+5OhrE8xPoihEIVQZBu9aCWla9JBnAT3hqrMp0r/Jec6aEgflSBSlbRWaygshHsYDyMgIeV8Y9qUwpa2+NczPfP5493amDXo2+GKHgaNPdmM2pprRFvy88HedjhjG+ezxOqVWMyPk5P4N1H4OrNfEqT/T6g+fG0D3e7gaAPP55P1prYf915aCNbeJ5MZ/uLJbN3/OJA98m1eefGFbfzRM8hrI2uQHBTcwJPPndHnU9o0bQ2CeCF//V30PeNEckLywH47JRQRejPFFtNIweriYxn3UNuHe8fBine5TgxhhjMLGCcRxgqIbjWbW+g9ryrQ3L6M+1npyFsn3rJDBbB4c49rCyHlShJXnBdDorlQeh6zgsA4QrSarxI78Zm8nzrBON6WwBwPRUXdP3x0rq9JbO1+/en+50xMwgaVvHjNwsDLsC4O446OQjcdaGbVK93nYQuPTCFCF2omm8OS3zXfJK4aOG6jyIB5zgbWTrCNZTVM2eweo737bvRoVNH2AzLTRNJpsuagGbi6tk8FjATSS6h+bg+hqsXDQIM/OKCutHScZGOdpOLu+Zexv+/C/QP2bW8RXyGazbmE48r3zy8bJAXr3K7WO9huW0MlElGDBvdkwsNzD0Y="
  # account email
  - secure: "kswOlX9r/BlK5KvxYUG/AZtvCpYNJExZJEjWqUZfB8moPJZuFF1HSN7IqYeakcWogmMb2vkjQuZrFAZE8JngBfzxhOAMws+WVkWeoSvzUHcBpH5fl+iVuyqNRCHECjbIUvGaF+AUz4xD/VizZ/rqwNi3dQTbDm+rznskjIew3IGGR54tC//Kq11fgGTklMCAM4sjp0Z15NHWkRG99NqddmSgvmYyW8QBzkAv4uGLzBp3DuNA70XdSSqK+nRDT5p2x/dfJotV02IgzZpczClLe/uS+Mp/jj5IyfrUE5n4tQKHAy/YsThBaq0oLLl42TUrBRFfGeqhGun8wd8WC+5n29GiAI2PxjXV3Q5k8gfIifCG85A736TS20q1iLAqJd1vhzTQLpIJOl/Kieuyh2clBSxHFdji6OBxDahvz2Twi88K6nMPM/xvr4kwv6bUbm30bNtMLEh++X+Ksxfplq6xT2EBdf5zfmPnG2W+Z9VoBxem+Gp7z6E6zjQsAdF9ps1bsc3ueUmVOlqvAi3Hkra4WlOpaqtT1ZFDey4xHhh+j7g82Rq+NgzRFnEpYoO09T6PkJQiCU8EzJFhYx03PwwMhYiiKPOpEJQGKbdyWlFX+GDlp69kHvMI1jnNDq+uj21FHCP3aNSJGO0YOuJ/YZSDp5XP9q1lA2nGPzMOZE/puSA="

before_install:
  - openssl aes-256-cbc -K $encrypted_9b768088574b_key -iv $encrypted_9b768088574b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine ${HOME}/.ssh/
  - chmod 0600 ${HOME}/.ssh/google_compute_engine

install:
  - pip install ansible==2.4.0 molecule testinfra apache-libcloud PyCrypto
  - ansible --version
  - molecule --version

script:
  - find tasks -type f -exec echo Validating {} \; -exec ansible-lint {} \;
  - molecule --debug create
  - molecule converge
  - molecule verify

after_script:
  - molecule destroy

notifications:
  email: false


