---
# tasks file for installing mongod

- name: Import repository key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
  tags:
    - mongo
    - mongo_install

- name: Add mongodb repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    filename: mongodb-org-3.2
    update_cache: yes
  tags:
    - mongo
    - mongo_install

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
  tags:
    - mongo
    - mongo_install

- name: enable mongodb
  systemd: name=mongod enabled=yes
  tags:
    - mongo
    - mongo_install
  